### 获取当前用户余额信息
GET http://127.0.0.1:9001/fox/fox-account-service/balance/current-balance
Content-Type: application/json
fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJqdGkiOiJkMzdiMmQxOC1jOGRlLTRkZjUtYjE4ZS1lYmZlMDNjYjAwY2QiLCJleHAiOjE2ODk1MjMyMDB9.oMSfswGPU2_jB41bpiorp73ea4qVd0q1XLqFEz7h4Y5bONJh2X0Qi-bn-UM_PbjQzi4VZiV0p6uV4wfJgE7IFF9ztyavMY0Lc7lESSHhl6AJ8xOa-ctRoISqej3b5qxJp2sS-wEtNNAAijN6NidOu2dmxvUMCH7WXuzqWtn-yx4Tfdlv-pmLT-XUGlqdDIrIr1wOfZTerPe8QD6Gip7og7940C7X7LzZ6NYeo2bp_uyLY7qD7mmqFr3Y8Fq9yaIQzTo5pXy041fa3-MWQmwF08QF7mr3LiwC87T60CGAYxYzRZd86Rz6rq35d5XA8M6dZQHCnpv-qlHC7Sk7Tpp1bQ

### 扣减用户余额
PUT http://127.0.0.1:9001/fox/fox-account-service/balance/deduct-balance
Content-Type: application/json
fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJqdGkiOiJkMzdiMmQxOC1jOGRlLTRkZjUtYjE4ZS1lYmZlMDNjYjAwY2QiLCJleHAiOjE2ODk1MjMyMDB9.oMSfswGPU2_jB41bpiorp73ea4qVd0q1XLqFEz7h4Y5bONJh2X0Qi-bn-UM_PbjQzi4VZiV0p6uV4wfJgE7IFF9ztyavMY0Lc7lESSHhl6AJ8xOa-ctRoISqej3b5qxJp2sS-wEtNNAAijN6NidOu2dmxvUMCH7WXuzqWtn-yx4Tfdlv-pmLT-XUGlqdDIrIr1wOfZTerPe8QD6Gip7og7940C7X7LzZ6NYeo2bp_uyLY7qD7mmqFr3Y8Fq9yaIQzTo5pXy041fa3-MWQmwF08QF7mr3LiwC87T60CGAYxYzRZd86Rz6rq35d5XA8M6dZQHCnpv-qlHC7Sk7Tpp1bQ

{
  "userId": 10,
  "balance": 10
}