### rest-template
POST http://127.0.0.1:8000/fox-nacos-client/communication/rest-template
Content-Type: application/json

{
  "username": "admin",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}


### rest-template-load-balancer
POST http://127.0.0.1:8000/fox-nacos-client/communication/rest-template-load-balancer
Content-Type: application/json

{
  "username": "admin",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

### ribbon
POST http://127.0.0.1:8000/fox-nacos-client/communication/ribbon
Content-Type: application/json

{
  "username": "admin",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

### think-in-ribbon
POST http://127.0.0.1:8000/fox-nacos-client/communication/think-in-ribbon
Content-Type: application/json

{
  "username": "admin",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

### token-by-feign
POST http://127.0.0.1:8000/fox-nacos-client/communication/token-by-feign
Content-Type: application/json

{
  "username": "admin",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

### thinking-by-feign
POST http://127.0.0.1:8000/fox-nacos-client/communication/thinking-by-feign
Content-Type: application/json

{
  "username": "admin",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}
