### hystrix-command-annotation
GET http://127.0.0.1:8000/fox-nacos-client/hystrix/hystrix-command-annotation?serviceId=fox-nacos-client
Content-Type: application/json

### simple-hystrix-command
GET http://127.0.0.1:8000/fox-nacos-client/hystrix/simple-hystrix-command?serviceId=fox-nacos-client
Content-Type: application/json

### hystrix-observable-command
GET http://127.0.0.1:8000/fox-nacos-client/hystrix/hystrix-observable-command?serviceId=fox-nacos-client
Content-Type: application/json

### cache-hystrix-command
GET http://127.0.0.1:8000/fox-nacos-client/hystrix/cache-hystrix-command?serviceId=fox-nacos-client
Content-Type: application/json

### cache-annotation-01
GET http://127.0.0.1:8000/fox-nacos-client/hystrix/cache-annotation-01?serviceId=fox-nacos-client
Content-Type: application/json

### cache-annotation-02
GET http://127.0.0.1:8000/fox-nacos-client/hystrix/cache-annotation-02?serviceId=fox-nacos-client
Content-Type: application/json

### cache-annotation-03
GET http://127.0.0.1:8000/fox-nacos-client/hystrix/cache-annotation-03?serviceId=fox-nacos-client
Content-Type: application/json

### request-merge
GET http://127.0.0.1:8000/fox-nacos-client/hystrix/request-merge
Content-Type: application/json

### request-merge-annotation
GET http://127.0.0.1:8000/fox-nacos-client/hystrix/request-merge-annotation
Content-Type: application/json


