### 查询服务实例信息
GET http://127.0.0.1:8000/fox-nacos-client/nacos-client/service-instance
Accept: application/json

### Nacos client
GET 127.0.0.1:9001/fox/fox-nacos-client/nacos-client/service-instance?serviceId=fox-gateway
Content-Type: application/json
token: fox
fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJqdGkiOiI0MzdkNGI0MC0xNTAzLTQ1YTEtYjYwMC0wOGU0MzczYmEyZTAiLCJleHAiOjE2ODk0MzY4MDB9.uCnBB4_-7KC5I_T5d0Gkw8RGpFlOLw5a2phzm_alCcA3ja5d8PwF9ypCi8mrrAn052guLruoyW7fAV90hrKHfJhhXvDn_f3kz6vu0Wa_fiGB8EnUw9mfDTA4IgCgPwzzvMdKo8znZHMMPZxJePmIRNXz8ymXqgmXtXXdtXcwc63zoQbZVSVJ93VF2E7vk7x8007mKvtDnI9NZmmAx8jxqn6RurvL_v8jZSKz4LinnJTXeZL18dvICLsdsX4evAtZ9vQUVokjoHvSxhU5-n8N4g_xSj_3XxpuezzGwlmGflvMuKk9taX0vPW-SSGNbh6huJWGT5fWtfWBzzo_l8F9PQ


### 查看 Seluth 跟踪信息
GET 127.0.0.1:9001/fox/fox-nacos-client/sleuth/trace-info
Content-Type: application/json
token: fox
fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJqdGkiOiI0MzdkNGI0MC0xNTAzLTQ1YTEtYjYwMC0wOGU0MzczYmEyZTAiLCJleHAiOjE2ODk0MzY4MDB9.uCnBB4_-7KC5I_T5d0Gkw8RGpFlOLw5a2phzm_alCcA3ja5d8PwF9ypCi8mrrAn052guLruoyW7fAV90hrKHfJhhXvDn_f3kz6vu0Wa_fiGB8EnUw9mfDTA4IgCgPwzzvMdKo8znZHMMPZxJePmIRNXz8ymXqgmXtXXdtXcwc63zoQbZVSVJ93VF2E7vk7x8007mKvtDnI9NZmmAx8jxqn6RurvL_v8jZSKz4LinnJTXeZL18dvICLsdsX4evAtZ9vQUVokjoHvSxhU5-n8N4g_xSj_3XxpuezzGwlmGflvMuKk9taX0vPW-SSGNbh6huJWGT5fWtfWBzzo_l8F9PQ
