### 获取 Token
POST http://127.0.0.1:9001/fox/fox-nacos-client/communication/token-by-feign
Content-Type: application/json
fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJqdGkiOiJlYTg4MzcwZC1hZmE2LTQ3MGItOWYyZi0yNmYyM2IwYzcyNjMiLCJleHAiOjE2OTAzMDA4MDB9.QUnDaChB678g9pbtS7Ymp-m54uRGpaFvvHDOMH7cWg18ZaYwIBuG8ZFCuz6kzqrm9hf_weLKUdAF2Z6vcwLoH4jBz20AbjvdSpXp8RJ5fs0pme-8TqiJ7CwBe8e8zCSZ6vePdhjYzI3Y97jCa5fF8mf2xhDHKMttkpW3tv9vsGPmbhpWcIm_cY95kQdFYPibcdY2obWpbyMnH_KT3ToCTM3EyEczexlvJ1xpxa76y22MGtPW_wPzmqTfH3adpo0XPDfO-UC2x-XYwPYUGCtQiAkMfMnDdR1BxoIAlNmJIMNUI-e3Y99pNoe9cBQEafWOXXu8JNqK4M2HYLMqSVScbg
token: fox

{
  "username": "admin",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/fox/fox-nacos-client/hystrix/hystrix-command-annotation?serviceId=fox-nacos-client
Content-Type: application/json
fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJqdGkiOiJlYTg4MzcwZC1hZmE2LTQ3MGItOWYyZi0yNmYyM2IwYzcyNjMiLCJleHAiOjE2OTAzMDA4MDB9.QUnDaChB678g9pbtS7Ymp-m54uRGpaFvvHDOMH7cWg18ZaYwIBuG8ZFCuz6kzqrm9hf_weLKUdAF2Z6vcwLoH4jBz20AbjvdSpXp8RJ5fs0pme-8TqiJ7CwBe8e8zCSZ6vePdhjYzI3Y97jCa5fF8mf2xhDHKMttkpW3tv9vsGPmbhpWcIm_cY95kQdFYPibcdY2obWpbyMnH_KT3ToCTM3EyEczexlvJ1xpxa76y22MGtPW_wPzmqTfH3adpo0XPDfO-UC2x-XYwPYUGCtQiAkMfMnDdR1BxoIAlNmJIMNUI-e3Y99pNoe9cBQEafWOXXu8JNqK4M2HYLMqSVScbg
token: fox

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/fox/fox-nacos-client/hystrix/simple-hystrix-command?serviceId=fox-nacos-client
Content-Type: application/json
fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJqdGkiOiJlYTg4MzcwZC1hZmE2LTQ3MGItOWYyZi0yNmYyM2IwYzcyNjMiLCJleHAiOjE2OTAzMDA4MDB9.QUnDaChB678g9pbtS7Ymp-m54uRGpaFvvHDOMH7cWg18ZaYwIBuG8ZFCuz6kzqrm9hf_weLKUdAF2Z6vcwLoH4jBz20AbjvdSpXp8RJ5fs0pme-8TqiJ7CwBe8e8zCSZ6vePdhjYzI3Y97jCa5fF8mf2xhDHKMttkpW3tv9vsGPmbhpWcIm_cY95kQdFYPibcdY2obWpbyMnH_KT3ToCTM3EyEczexlvJ1xpxa76y22MGtPW_wPzmqTfH3adpo0XPDfO-UC2x-XYwPYUGCtQiAkMfMnDdR1BxoIAlNmJIMNUI-e3Y99pNoe9cBQEafWOXXu8JNqK4M2HYLMqSVScbg
token: fox

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/fox/fox-nacos-client/hystrix/hystrix-observable-command?serviceId=fox-nacos-client
Content-Type: application/json
fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJqdGkiOiJlYTg4MzcwZC1hZmE2LTQ3MGItOWYyZi0yNmYyM2IwYzcyNjMiLCJleHAiOjE2OTAzMDA4MDB9.QUnDaChB678g9pbtS7Ymp-m54uRGpaFvvHDOMH7cWg18ZaYwIBuG8ZFCuz6kzqrm9hf_weLKUdAF2Z6vcwLoH4jBz20AbjvdSpXp8RJ5fs0pme-8TqiJ7CwBe8e8zCSZ6vePdhjYzI3Y97jCa5fF8mf2xhDHKMttkpW3tv9vsGPmbhpWcIm_cY95kQdFYPibcdY2obWpbyMnH_KT3ToCTM3EyEczexlvJ1xpxa76y22MGtPW_wPzmqTfH3adpo0XPDfO-UC2x-XYwPYUGCtQiAkMfMnDdR1BxoIAlNmJIMNUI-e3Y99pNoe9cBQEafWOXXu8JNqK4M2HYLMqSVScbg
token: fox
