### 创建订单
POST http://127.0.0.1:9001/fox/fox-order-service/order/create-order
Content-Type: application/json
Accept: application/json
fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJqdGkiOiJmMmRkNjlhOS01ZjllLTQxNjItYTlkZS1mYmY2MTgxM2ZjMTYiLCJleHAiOjE2OTA1NjAwMDB9.faJ9_r3NsQlgkeJP9PehGyqrH1UHkOnscM0xFgQnXu3538DKSbgV3Ng91R6F6bJKz2huGyasS7fnD6dGCTfQTy2_O6fWsRArvmckM0S9D4U1YZKa7lzswvT5MzqOYM1EokGKtCBNtBWNYD3xvjKXcU9c3wbpDxu_3dJ5K-lAG04-dxbGo5gtNqUzLQdcOUgh7LevWeXueKPf0JvQsiNjTY4wIiibFMqaipwbN6cy_Mh41qn9-i8t_tBWvOzls0c107HL9FN47BtAG7oxnwF8yrWbuT-mMzWRLG2U7P5EQ-4x0zLWJTM-rLavtOvC6sePcts1YLYrZw5TWQ3u5c5sYA

{
  "userAddress": 10,
  "orderItems": [
    {
      "goodsId": 10,
      "count": 5
    }
  ]
}

### 查询订单
GET http://127.0.0.1:9001/fox/fox-order-service/order/order-detail?page=1
Accept: application/json
fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTAsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIn0iLCJqdGkiOiJmMmRkNjlhOS01ZjllLTQxNjItYTlkZS1mYmY2MTgxM2ZjMTYiLCJleHAiOjE2OTA1NjAwMDB9.faJ9_r3NsQlgkeJP9PehGyqrH1UHkOnscM0xFgQnXu3538DKSbgV3Ng91R6F6bJKz2huGyasS7fnD6dGCTfQTy2_O6fWsRArvmckM0S9D4U1YZKa7lzswvT5MzqOYM1EokGKtCBNtBWNYD3xvjKXcU9c3wbpDxu_3dJ5K-lAG04-dxbGo5gtNqUzLQdcOUgh7LevWeXueKPf0JvQsiNjTY4wIiibFMqaipwbN6cy_Mh41qn9-i8t_tBWvOzls0c107HL9FN47BtAG7oxnwF8yrWbuT-mMzWRLG2U7P5EQ-4x0zLWJTM-rLavtOvC6sePcts1YLYrZw5TWQ3u5c5sYA
