### actuator
GET 127.0.0.1:9001/fox/fox-gateway/actuator
Content-Type: application/json
### token: fox
### fox-user: eyJhbGciOiJSUzI1NiJ9.eyJmb3gtdXNlciI6IntcImlkXCI6MTMsXCJ1c2VybmFtZVwiOlwiYWRtaW4xXCJ9IiwianRpIjoiNDMyNWZiNWQtODBiZS00NjY3LWE3ZGMtOTNkNzdhZmEyYWI3IiwiZXhwIjoxNjg5MzUwNDAwfQ.aGHalmYOIg63QJvuneCa519kvZwzWcz86rtYi27enHqd8yRT9LgnOm8i6EtZ2C1zL6LAsZWn_AYEz1HWx81uGnxou6HeIcEQZr_Dn3OcK7MVGSMMERjuPbcPK4BFFa-hLXYoOA_D7g1UyJhTyK5T5zL2B2NkkFVedD0M0XKtbAqwbCWA9f9SfCiuFDM1tU49AmKNeSGZrSFiOWdoOhrAd5UVXC8bc34fSYKdlP7ao2j4khbDVHzeQOjU_uHPKX53ZcS-Guq5Npik81sjiedSdMCQKn2aYaJOqODBr_RXXMexrgj-lvvDART6vIXR73kMZHu20hlrjwEd28xosd5E0w

